apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels: {{ - include "keycloak-entitlements-service.labels" . | nindent 4 }}
data: {{ - toYaml .Values.configmap.data | nindent 2 }}
